route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - channel: '#promtheous'
            api_url: 'https://hooks.slack.com/services/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'
